[tools]
bun = "latest"

[tasks]
install = "bun install --cwd frontend && bun install --cwd backend"
dev = "bunx concurrently \"mise run dev-frontend\" \"mise run dev-backend\""
dev-frontend = "bun run --cwd frontend dev"
dev-backend = "bun run --cwd backend dev"
build = "bun run --cwd frontend build && bun run --cwd backend build"
db-migrate = "bun run --cwd backend migrate"
db-seed = "bun run --cwd backend seed"